-- Full public-schema snapshot of the live Clicktide Supabase (hmihfncvahsdlmefyxyg)
-- Generated 2026-06-11. Additive/idempotent where possible: tables use IF NOT EXISTS,
-- PKs are wrapped in exception-swallowing DO blocks, functions are CREATE OR REPLACE,
-- triggers/policies are drop-then-create. Purpose: a fresh Supabase project can be
-- brought to parity by running this file, per cross-check finding that GitHub lagged
-- the live schema (gift_auto_send, google_review_url, dashboard_color/bg,
-- address_request_token, alerts, campaign_sends, message_events, survey_responses,
-- email_templates, plan-limit trigger, etc.).

-- ============ TABLES ============

create table if not exists public.ai_suggestions ("id" uuid not null default gen_random_uuid(), "user_id" uuid not null, "title" text not null, "campaign_type" text not null default 'message_only'::text, "trigger_text" text not null, "gift_name" text, "gift_cost" numeric default 0, "message" text, "rationale" text, "projected" text, "status" text not null default 'suggested'::text, "created_at" timestamp with time zone not null default now());

create table if not exists public.alerts ("id" bigint generated by default as identity, "business_id" text, "customer_id" bigint, "type" text, "message" text, "resolved" boolean default false, "created_at" timestamp with time zone default now(), "user_id" uuid);

create table if not exists public.campaign_sends ("id" uuid not null default gen_random_uuid(), "user_id" uuid not null, "campaign_id" bigint not null, "customer_id" bigint not null, "channel" text not null, "status" text not null default 'sent'::text, "detail" text, "sent_at" timestamp with time zone not null default now());

create table if not exists public.campaigns ("id" bigint generated by default as identity, "created_at" timestamp with time zone not null default now(), "business_id" text, "name" text, "trigger" text, "gift_name" text, "gift_cost" real, "status" text, "platform" text, "user_id" uuid, "campaign_type" text, "message" text, "delay_days" integer default 0, "cancel_on_refund" boolean default true, "min_spend" real default 0, "cooldown_days" integer default 30, "product_trigger" text, "min_order_val" real default 0, "gift_catalog_id" uuid, "printify_product_id" text, "printify_variant_id" integer, "gift_image_url" text, "delivery_channel" text default 'email'::text, "sms_message" text, "postcard_design" text default 'bold'::text);

create table if not exists public.clicktide ("id" bigint generated by default as identity, "created_at" timestamp with time zone not null default now(), "email" text, "business_name" text, "plan" text, "churn_days" integer default 60, "business_type" text, "wallet_balance" numeric default 0, "user_id" uuid, "phone" text, "address" text, "city" text, "state" text, "zip" text, "website" text, "onboarding_complete" boolean default false, "help_email_sent" boolean default false, "contact_name" text, "business_phone" text, "business_email" text, "stripe_customer_id" text, "stripe_subscription_id" text, "stripe_subscription_status" text, "stripe_price_id" text, "stripe_current_period_end" timestamp with time zone, "legal_terms_accepted_at" timestamp with time zone, "legal_terms_version" text, "legal_authorized_services" boolean default false, "logo_url" text, "welcome_email_sent" boolean default false, "gift_auto_send" boolean default false, "google_review_url" text, "dashboard_color" text, "dashboard_bg" text);

-- Sequence required by clicktide_admin_audit_log's id default (live table predates identity columns).
create sequence if not exists public.clicktide_admin_audit_log_id_seq;
create table if not exists public.clicktide_admin_audit_log ("id" bigint not null default nextval('clicktide_admin_audit_log_id_seq'::regclass), "actor_user_id" uuid, "client_user_id" uuid, "action" text not null, "target_table" text, "target_id" text, "details" jsonb not null default '{}'::jsonb, "created_at" timestamp with time zone not null default now());

create table if not exists public.clicktide_partner_clients ("partner_user_id" uuid not null, "client_user_id" uuid not null, "can_onboard" boolean not null default true, "can_support" boolean not null default true, "can_manage_campaigns" boolean not null default true, "can_manage_fulfillment" boolean not null default true, "is_active" boolean not null default true, "created_at" timestamp with time zone not null default now());

create table if not exists public.clicktide_staff ("user_id" uuid not null, "role" text not null, "is_active" boolean not null default true, "created_at" timestamp with time zone not null default now());

create table if not exists public.customers ("id" bigint generated by default as identity, "created_at" timestamp with time zone not null default now(), "business_id" text, "name" text, "email" text, "last_vist" date, "total_spent" real, "status" text, "visits" integer default 0, "order_count" integer default 0, "satisfaction_score" integer, "prev_satisfaction_score" integer, "last_visit_at" timestamp with time zone, "last_order_at" timestamp with time zone, "last_survey_at" timestamp with time zone, "loyalty_score" integer, "loyalty_tier" text, "last_scored_at" timestamp with time zone, "user_id" uuid, "phone" text, "sms_consent" boolean default false, "sms_consent_at" timestamp with time zone, "sms_unsubscribed_at" timestamp with time zone, "address" text, "city" text, "state" text, "zip" text, "address_request_token" uuid default gen_random_uuid(), "address_requested_at" timestamp with time zone, "address_confirmed_at" timestamp with time zone);

create table if not exists public.email_templates ("id" uuid not null default gen_random_uuid(), "user_id" uuid not null default auth.uid(), "name" text not null default 'Default'::text, "subject" text, "blocks" jsonb not null default '[]'::jsonb, "brand" jsonb not null default '{}'::jsonb, "updated_at" timestamp with time zone not null default now());

create table if not exists public.gift_catalog ("id" uuid not null default gen_random_uuid(), "name" text not null, "subtitle" text, "category" text not null default 'general'::text, "image_url" text, "estimated_cost" numeric not null default 0, "currency" text not null default 'USD'::text, "printify_product_id" text, "printify_variant_id" integer, "printify_blueprint_id" text, "print_provider_id" text, "is_active" boolean not null default true, "is_featured" boolean not null default false, "source" text not null default 'manual'::text, "raw" jsonb not null default '{}'::jsonb, "created_at" timestamp with time zone not null default now(), "updated_at" timestamp with time zone not null default now());

create table if not exists public.message_events ("id" uuid not null default gen_random_uuid(), "provider" text not null default 'resend'::text, "provider_message_id" text not null, "event_type" text not null, "user_id" uuid, "campaign_id" bigint, "customer_id" bigint, "occurred_at" timestamp with time zone default now(), "raw" jsonb default '{}'::jsonb, "created_at" timestamp with time zone not null default now());

create table if not exists public.oauth_states ("id" uuid not null default gen_random_uuid(), "state" text not null, "user_id" uuid, "platform" text not null, "metadata" jsonb default '{}'::jsonb, "expires_at" timestamp with time zone not null default (now() + '00:10:00'::interval), "created_at" timestamp with time zone not null default now());

create table if not exists public.platform_connections ("id" uuid not null default gen_random_uuid(), "user_id" uuid, "platform" text not null, "merchant_id" text not null, "merchant_name" text, "shop_domain" text, "access_token" text not null, "refresh_token" text, "token_expires_at" timestamp with time zone, "scope" text, "raw_response" jsonb default '{}'::jsonb, "connected_at" timestamp with time zone not null default now(), "updated_at" timestamp with time zone not null default now(), "is_active" boolean not null default true, "last_synced_at" timestamp with time zone);

create table if not exists public.printify_products ("id" uuid not null default gen_random_uuid(), "merchant_id" uuid not null, "gift_type" text not null, "printify_product_id" text not null, "variant_id" integer not null, "created_at" timestamp with time zone not null default now());

create table if not exists public.shipments ("id" bigint generated by default as identity, "created_at" timestamp with time zone not null default now(), "business_id" text, "customer_name" text, "gift" text, "campaign" text, "status" text, "tracking" text, "platform" text, "printify_order_id" text, "merchant_id" uuid, "customer_email" text, "address" jsonb, "customer_id" bigint, "gift_type" text, "tier" text, "reason" text, "user_id" uuid);

create table if not exists public.sms_messages ("id" uuid not null default gen_random_uuid(), "user_id" uuid not null, "campaign_id" bigint, "customer_id" bigint, "to_phone" text not null, "body" text not null, "status" text not null default 'queued'::text, "provider" text not null default 'twilio'::text, "provider_message_id" text, "error" text, "sent_at" timestamp with time zone, "created_at" timestamp with time zone not null default now());

create table if not exists public.stripe_webhook_events ("id" text not null, "event_type" text not null, "processed_at" timestamp with time zone not null default now());

create table if not exists public.support_chats ("id" uuid not null default gen_random_uuid(), "session_id" text not null, "user_id" uuid, "role" text not null, "content" text not null, "created_at" timestamp with time zone not null default now());

create table if not exists public.survey_responses ("id" bigint generated by default as identity, "business_id" text, "customer_id" bigint, "rating" integer, "previous_rating" integer, "created_at" timestamp with time zone default now(), "user_id" uuid);

create table if not exists public.wallet ("id" bigint generated by default as identity, "created_at" timestamp with time zone not null default now(), "business_id" text, "balance" real, "last_topup" timestamp with time zone, "user_id" uuid, "desc" text, "amount" real default 0, "transaction_type" text default 'adjustment'::text, "note" text, "created_by" uuid, "stripe_session_id" text, "stripe_payment_intent_id" text, "stripe_customer_id" text, "status" text default 'posted'::text, "reference_id" text);

-- ============ PRIMARY KEYS ============

do $$ begin alter table public."ai_suggestions" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."alerts" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."campaign_sends" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."campaigns" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."clicktide" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."clicktide_admin_audit_log" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."clicktide_partner_clients" add primary key ("partner_user_id", "client_user_id"); exception when others then null; end $$;
do $$ begin alter table public."clicktide_staff" add primary key ("user_id"); exception when others then null; end $$;
do $$ begin alter table public."customers" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."email_templates" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."gift_catalog" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."message_events" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."oauth_states" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."platform_connections" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."printify_products" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."shipments" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."sms_messages" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."stripe_webhook_events" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."support_chats" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."survey_responses" add primary key ("id"); exception when others then null; end $$;
do $$ begin alter table public."wallet" add primary key ("id"); exception when others then null; end $$;

-- ============ INDEXES ============

CREATE INDEX IF NOT EXISTS ai_suggestions_user ON public.ai_suggestions USING btree (user_id, status);
CREATE INDEX IF NOT EXISTS campaign_sends_lookup ON public.campaign_sends USING btree (user_id, campaign_id, customer_id, sent_at DESC);
CREATE INDEX IF NOT EXISTS customers_address_request_token_idx ON public.customers USING btree (address_request_token);
CREATE UNIQUE INDEX IF NOT EXISTS email_templates_user_name ON public.email_templates USING btree (user_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS gift_catalog_printify_variant_unique ON public.gift_catalog USING btree (printify_product_id, printify_variant_id) WHERE ((printify_product_id IS NOT NULL) AND (printify_variant_id IS NOT NULL));
CREATE INDEX IF NOT EXISTS idx_alerts_business ON public.alerts USING btree (business_id);
CREATE INDEX IF NOT EXISTS idx_customers_business ON public.customers USING btree (business_id);
CREATE INDEX IF NOT EXISTS idx_oauth_states_state ON public.oauth_states USING btree (state);
CREATE INDEX IF NOT EXISTS idx_platform_connections_user ON public.platform_connections USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_printify_products_merchant ON public.printify_products USING btree (merchant_id, gift_type);
CREATE INDEX IF NOT EXISTS idx_shipments_customer ON public.shipments USING btree (customer_id);
CREATE UNIQUE INDEX IF NOT EXISTS message_events_dedupe ON public.message_events USING btree (provider_message_id, event_type);
CREATE INDEX IF NOT EXISTS message_events_user ON public.message_events USING btree (user_id, campaign_id);
CREATE UNIQUE INDEX IF NOT EXISTS oauth_states_state_key ON public.oauth_states USING btree (state);
CREATE UNIQUE INDEX IF NOT EXISTS platform_connections_user_id_platform_merchant_id_key ON public.platform_connections USING btree (user_id, platform, merchant_id);
CREATE UNIQUE INDEX IF NOT EXISTS printify_products_merchant_id_gift_type_key ON public.printify_products USING btree (merchant_id, gift_type);
CREATE INDEX IF NOT EXISTS support_chats_session ON public.support_chats USING btree (session_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS wallet_stripe_session_id_unique ON public.wallet USING btree (stripe_session_id) WHERE (stripe_session_id IS NOT NULL);

-- ============ FUNCTIONS ============

CREATE OR REPLACE FUNCTION public.clicktide_can_access_client(client_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select
    auth.uid() = client_id
    or exists (
      select 1
      from public.clicktide_staff s
      where s.user_id = auth.uid()
        and s.is_active
        and s.role in ('admin', 'support')
    )
    or exists (
      select 1
      from public.clicktide_staff s
      join public.clicktide_partner_clients pc
        on pc.partner_user_id = s.user_id
      where s.user_id = auth.uid()
        and s.is_active
        and s.role = 'partner'
        and pc.client_user_id = client_id
        and pc.is_active
    );
$function$
;

CREATE OR REPLACE FUNCTION public.clicktide_can_manage_fulfillment(client_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select
    exists (
      select 1
      from public.clicktide_staff s
      where s.user_id = auth.uid()
        and s.is_active
        and s.role in ('admin', 'support')
    )
    or exists (
      select 1
      from public.clicktide_staff s
      join public.clicktide_partner_clients pc
        on pc.partner_user_id = s.user_id
      where s.user_id = auth.uid()
        and s.is_active
        and s.role = 'partner'
        and pc.client_user_id = client_id
        and pc.can_manage_fulfillment
        and pc.is_active
    );
$function$
;

CREATE OR REPLACE FUNCTION public.clicktide_debit_gift_wallet(client_id uuid, debit_amount numeric, description text, reference text DEFAULT NULL::text)
 RETURNS numeric
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  current_balance numeric;
  new_balance numeric;
begin
  if client_id is null then
    raise exception 'Client id is required';
  end if;

  if debit_amount is null or debit_amount <= 0 then
    raise exception 'Debit amount must be greater than zero';
  end if;

  if auth.uid() is null then
    raise exception 'Not allowed to debit this wallet';
  end if;

  if auth.uid() is distinct from client_id and not public.clicktide_can_manage_fulfillment(client_id) then
    raise exception 'Not allowed to debit this wallet';
  end if;

  select public.clicktide_wallet_balance(client_id) into current_balance;

  if current_balance < debit_amount then
    raise exception 'Insufficient gift wallet balance';
  end if;

  new_balance := current_balance - debit_amount;

  insert into public.wallet (
    user_id,
    "desc",
    amount,
    balance,
    transaction_type,
    status,
    reference_id
  ) values (
    client_id,
    coalesce(nullif(description, ''), 'Gift sent'),
    -debit_amount,
    new_balance,
    'gift_debit',
    'posted',
    reference
  );

  return new_balance;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.clicktide_debit_gift_wallet_server(client_id uuid, debit_amount numeric, description text, reference text DEFAULT NULL::text)
 RETURNS numeric
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  current_balance numeric;
  new_balance numeric;
begin
  if client_id is null then
    raise exception 'Client id is required';
  end if;

  if debit_amount is null or debit_amount <= 0 then
    raise exception 'Debit amount must be greater than zero';
  end if;

  select public.clicktide_wallet_balance(client_id) into current_balance;

  if current_balance < debit_amount then
    raise exception 'Insufficient gift wallet balance';
  end if;

  new_balance := current_balance - debit_amount;

  insert into public.wallet (
    user_id,
    "desc",
    amount,
    balance,
    transaction_type,
    status,
    reference_id
  ) values (
    client_id,
    coalesce(nullif(description, ''), 'Gift sent'),
    -debit_amount,
    new_balance,
    'gift_debit',
    'posted',
    reference
  );

  return new_balance;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.clicktide_internal_key()
 RETURNS text
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select decrypted_secret from vault.decrypted_secrets where name = 'CAMPAIGN_RUNNER_KEY' limit 1;
$function$
;

CREATE OR REPLACE FUNCTION public.clicktide_is_staff(required_roles text[] DEFAULT ARRAY['admin'::text, 'support'::text, 'partner'::text])
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.clicktide_staff s
    where s.user_id = auth.uid()
      and s.is_active
      and s.role = any(required_roles)
  );
$function$
;

CREATE OR REPLACE FUNCTION public.clicktide_wallet_balance(client_id uuid)
 RETURNS numeric
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce((
    select balance
    from public.wallet
    where user_id = client_id
    order by created_at desc
    limit 1
  ), 0)::numeric;
$function$
;

CREATE OR REPLACE FUNCTION public.enforce_customer_cap()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  p text;
  cap integer;
  n integer;
begin
  if NEW.user_id is null then
    return NEW; -- legacy/demo rows
  end if;
  select lower(coalesce(plan,'')) into p from clicktide where user_id = NEW.user_id limit 1;
  cap := case p
    when 'local' then 200
    when 'growth' then 1000
    when 'scale' then null
    else 200
  end;
  if cap is not null then
    select count(*) into n from customers where user_id = NEW.user_id;
    if n >= cap then
      raise exception 'PLAN_CUSTOMER_LIMIT_REACHED: your plan allows % customers. Upgrade to add more.', cap;
    end if;
  end if;
  return NEW;
end;
$function$
;

-- ============ TRIGGERS ============

drop trigger if exists customers_plan_cap on public."customers"; CREATE TRIGGER customers_plan_cap BEFORE INSERT ON public.customers FOR EACH ROW EXECUTE FUNCTION enforce_customer_cap();

-- ============ ROW LEVEL SECURITY ============

alter table public."ai_suggestions" enable row level security;
alter table public."alerts" enable row level security;
alter table public."campaign_sends" enable row level security;
alter table public."campaigns" enable row level security;
alter table public."clicktide" enable row level security;
alter table public."clicktide_admin_audit_log" enable row level security;
alter table public."clicktide_partner_clients" enable row level security;
alter table public."clicktide_staff" enable row level security;
alter table public."customers" enable row level security;
alter table public."email_templates" enable row level security;
alter table public."gift_catalog" enable row level security;
alter table public."message_events" enable row level security;
alter table public."oauth_states" enable row level security;
alter table public."platform_connections" enable row level security;
alter table public."printify_products" enable row level security;
alter table public."shipments" enable row level security;
alter table public."sms_messages" enable row level security;
alter table public."stripe_webhook_events" enable row level security;
alter table public."support_chats" enable row level security;
alter table public."survey_responses" enable row level security;
alter table public."wallet" enable row level security;

-- ============ POLICIES ============

drop policy if exists "own suggestions select" on public."ai_suggestions"; create policy "own suggestions select" on public."ai_suggestions" as permissive for select to public using ((auth.uid() = user_id));
drop policy if exists "own suggestions update" on public."ai_suggestions"; create policy "own suggestions update" on public."ai_suggestions" as permissive for update to public using ((auth.uid() = user_id));
drop policy if exists "own alerts select" on public."alerts"; create policy "own alerts select" on public."alerts" as permissive for select to public using ((auth.uid() = user_id));
drop policy if exists "own alerts update" on public."alerts"; create policy "own alerts update" on public."alerts" as permissive for update to public using ((auth.uid() = user_id));
drop policy if exists "Businesses read own campaign sends" on public."campaign_sends"; create policy "Businesses read own campaign sends" on public."campaign_sends" as permissive for select to public using ((auth.uid() = user_id));
drop policy if exists "campaigns_staff_client_access" on public."campaigns"; create policy "campaigns_staff_client_access" on public."campaigns" as permissive for all to public using (clicktide_can_access_client(user_id)) with check (clicktide_can_access_client(user_id));
drop policy if exists "campaigns_user_all" on public."campaigns"; create policy "campaigns_user_all" on public."campaigns" as permissive for all to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
drop policy if exists "clicktide_staff_client_access" on public."clicktide"; create policy "clicktide_staff_client_access" on public."clicktide" as permissive for all to public using (clicktide_can_access_client(user_id)) with check (clicktide_can_access_client(user_id));
drop policy if exists "clicktide_user_all" on public."clicktide"; create policy "clicktide_user_all" on public."clicktide" as permissive for all to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
drop policy if exists "audit_staff_insert" on public."clicktide_admin_audit_log"; create policy "audit_staff_insert" on public."clicktide_admin_audit_log" as permissive for insert to public with check (clicktide_is_staff(ARRAY['admin'::text, 'support'::text, 'partner'::text]));
drop policy if exists "audit_staff_read" on public."clicktide_admin_audit_log"; create policy "audit_staff_read" on public."clicktide_admin_audit_log" as permissive for select to public using (clicktide_is_staff(ARRAY['admin'::text, 'support'::text]));
drop policy if exists "partner_clients_admin_write" on public."clicktide_partner_clients"; create policy "partner_clients_admin_write" on public."clicktide_partner_clients" as permissive for all to public using (clicktide_is_staff(ARRAY['admin'::text, 'support'::text])) with check (clicktide_is_staff(ARRAY['admin'::text, 'support'::text]));
drop policy if exists "partner_clients_staff_read" on public."clicktide_partner_clients"; create policy "partner_clients_staff_read" on public."clicktide_partner_clients" as permissive for select to public using ((clicktide_is_staff(ARRAY['admin'::text, 'support'::text]) OR (partner_user_id = auth.uid())));
drop policy if exists "staff_admin_read" on public."clicktide_staff"; create policy "staff_admin_read" on public."clicktide_staff" as permissive for select to public using (clicktide_is_staff(ARRAY['admin'::text, 'support'::text]));
drop policy if exists "staff_admin_write" on public."clicktide_staff"; create policy "staff_admin_write" on public."clicktide_staff" as permissive for all to public using (clicktide_is_staff(ARRAY['admin'::text])) with check (clicktide_is_staff(ARRAY['admin'::text]));
drop policy if exists "customers_staff_client_access" on public."customers"; create policy "customers_staff_client_access" on public."customers" as permissive for all to public using (clicktide_can_access_client(user_id)) with check (clicktide_can_access_client(user_id));
drop policy if exists "customers_user_all" on public."customers"; create policy "customers_user_all" on public."customers" as permissive for all to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
drop policy if exists "own templates delete" on public."email_templates"; create policy "own templates delete" on public."email_templates" as permissive for delete to public using ((auth.uid() = user_id));
drop policy if exists "own templates insert" on public."email_templates"; create policy "own templates insert" on public."email_templates" as permissive for insert to public with check ((auth.uid() = user_id));
drop policy if exists "own templates select" on public."email_templates"; create policy "own templates select" on public."email_templates" as permissive for select to public using ((auth.uid() = user_id));
drop policy if exists "own templates update" on public."email_templates"; create policy "own templates update" on public."email_templates" as permissive for update to public using ((auth.uid() = user_id));
drop policy if exists "gift_catalog_active_read" on public."gift_catalog"; create policy "gift_catalog_active_read" on public."gift_catalog" as permissive for select to public using ((is_active OR clicktide_is_staff(ARRAY['admin'::text, 'support'::text, 'partner'::text])));
drop policy if exists "gift_catalog_staff_write" on public."gift_catalog"; create policy "gift_catalog_staff_write" on public."gift_catalog" as permissive for all to public using (clicktide_is_staff(ARRAY['admin'::text, 'support'::text])) with check (clicktide_is_staff(ARRAY['admin'::text, 'support'::text]));
drop policy if exists "own events select" on public."message_events"; create policy "own events select" on public."message_events" as permissive for select to public using ((auth.uid() = user_id));
drop policy if exists "oauth_states_staff_client_access" on public."oauth_states"; create policy "oauth_states_staff_client_access" on public."oauth_states" as permissive for all to public using (clicktide_can_access_client(user_id)) with check (clicktide_can_access_client(user_id));
drop policy if exists "oauth_states_user_all" on public."oauth_states"; create policy "oauth_states_user_all" on public."oauth_states" as permissive for all to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
drop policy if exists "Users read own connections" on public."platform_connections"; create policy "Users read own connections" on public."platform_connections" as permissive for select to public using ((auth.uid() = user_id));
drop policy if exists "platform_connections_staff_client_access" on public."platform_connections"; create policy "platform_connections_staff_client_access" on public."platform_connections" as permissive for all to public using (clicktide_can_access_client(user_id)) with check (clicktide_can_access_client(user_id));
drop policy if exists "platform_connections_user_all" on public."platform_connections"; create policy "platform_connections_user_all" on public."platform_connections" as permissive for all to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
drop policy if exists "shipments_staff_client_access" on public."shipments"; create policy "shipments_staff_client_access" on public."shipments" as permissive for all to public using (clicktide_can_access_client(user_id)) with check (clicktide_can_access_client(user_id));
drop policy if exists "shipments_user_all" on public."shipments"; create policy "shipments_user_all" on public."shipments" as permissive for all to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
drop policy if exists "sms_messages_staff_all" on public."sms_messages"; create policy "sms_messages_staff_all" on public."sms_messages" as permissive for all to public using (clicktide_is_staff(ARRAY['admin'::text, 'support'::text, 'partner'::text])) with check (clicktide_is_staff(ARRAY['admin'::text, 'support'::text, 'partner'::text]));
drop policy if exists "sms_messages_user_all" on public."sms_messages"; create policy "sms_messages_user_all" on public."sms_messages" as permissive for all to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
drop policy if exists "own survey responses select" on public."survey_responses"; create policy "own survey responses select" on public."survey_responses" as permissive for select to public using ((auth.uid() = user_id));
drop policy if exists "wallet_staff_client_access" on public."wallet"; create policy "wallet_staff_client_access" on public."wallet" as permissive for all to public using (clicktide_can_access_client(user_id)) with check (clicktide_can_access_client(user_id));
drop policy if exists "wallet_user_all" on public."wallet"; create policy "wallet_user_all" on public."wallet" as permissive for all to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
